### PR TITLE
Connection: Fix unexpected server disconnection due to OpenSSL thread safety problems

### PR DESCRIPTION
**Pull request by botanegg**
Its a dirty 15 minutes quick fix to show the idea

OpenSSL FAQ https://www.openssl.org/docs/faq.html said about only one thread should use a socket

Partially_Closes #7

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
The failing CI should be fixed by rebasing against current master branch.

@davidebeatrici what is the plan with this PR?

**Comment by davidebeatrici** [comment]
I'm a bit concerned about locking in a function that may be called several times in a second... maybe we should let the decision up to the API user.

**Comment by Krzmbrzl** [comment]
> maybe we should let the decision up to the API user.

I vote strongly against that. If OpenSSL explicitly states that one should use single-thread access, then that's exactly what we should do.
I think the best approach would be to have the socket handling (reading and writing) in a single thread (that only does this) and then all processing happens in different threads and once they want to send something, they queue their message in some sort of queue that is processed by the socket thread sequentially.
If I'm not mistaken, socket operations can't be performed in parallel on hardware-level anyway.

**Comment by davidebeatrici** [comment]
Well, that's what we do inside the library itself.

It's the example code that has to be fixed...

**Comment by botanegg** [comment]
Sounds good, but I dont know about my time to implement Krzmbrzl approach

**Comment by Krzmbrzl** [comment]
I'm wondering though: does this even have to be part of the public API? Individual connections and especially writing data to the respective sockets seems like something that should be abstracted away by the library, doesn't it?
If we remove it from the public interface, we can simply ensure that it is used properly internally and be done with it. If we leave it in the public API, then I guess the way to go would be to state that these functions must only ever by accessed from a single thread, but that is kinda ugly and it is likely that downstream users will mess it up :thinking:

**Comment by davidebeatrici** [comment]
Connections can be added to `Peer` for automatic management, but data still has to be sent through the specific connection's function.

**Comment by Krzmbrzl** [comment]
Correct, but if we don't expose that to the end user, that's one thing less to worry about. Then we can manage the threading internally and keep the library users out of it.
And then we can figure out a way to nicely implement the worker+sender threads

**Comment by davidebeatrici** [comment]
While using the library for a new project I encountered the issue several times, thus I decided to rebase this and merge it right away.

My initial comment is still valid, but I vastly overestimated the cost of acquiring and releasing a mutex.

@botanegg The fix you proposed is simple and effective. @Krzmbrzl's idea would avoid the need for a mutex, but it adds quite some complexity and is actually not guaranteed to be the best mechanism in terms of performance.

**Pull request merged**
